# Generated by Django 5.2.7 on 2025-12-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='grau',
            field=models.CharField(choices=[('licenciatura', 'Licenciatura'), ('mestrado', 'Mestrado'), ('doutoramento', 'Doutoramento'), ('especialidade', 'Especialidade')], default='licenciatura', max_length=20, verbose_name='Grau'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('semipresencial', 'Semipresencial'), ('ead', 'EAD')], default='presencial', max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='curso',
            name='regime',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('pos-laboral', 'Pós-Laboral')], default='diurno', max_length=20, verbose_name='Regime'),
        ),
    ]
