# Generated by Django 5.2.9 on 2025-12-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_curso_grau_curso_modalidade_curso_regime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['curso', 'ano_curricular', 'semestre_curricular', 'nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ano_curricular',
            field=models.PositiveIntegerField(default=1, verbose_name='Ano Curricular'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestre_curricular',
            field=models.PositiveIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], default=1, verbose_name='Semestre Curricular'),
        ),
    ]
