# Generated by Django 5.2.9 on 2025-12-31 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_disciplina_options_disciplina_ano_curricular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='documentos_entregues',
            field=models.BooleanField(default=False, verbose_name='Documentação Entregue'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudantes/fotos/', verbose_name='Foto do Estudante'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='login_usuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Login de Acesso'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='matricula_bloqueada',
            field=models.BooleanField(default=False, verbose_name='Matrícula Bloqueada?'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='notificacoes_email',
            field=models.BooleanField(default=True, verbose_name='Receber Notificações por Email'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='notificacoes_sms',
            field=models.BooleanField(default=False, verbose_name='Receber Notificações por SMS'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='observacoes_documentacao',
            field=models.TextField(blank=True, verbose_name='Observações de Documentação'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='senha_provisoria',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha Provisória'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(default='Ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone_alternativo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Alternativo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
