# Generated by Django 5.2.9 on 2025-12-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_responsaveis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='receber_emails_sistema',
            field=models.BooleanField(default=True, verbose_name='Deseja receber emails do sistema?'),
        ),
    ]
