# Generated by Django 5.2.9 on 2026-01-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_inscricao_tipo_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoescola',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='escola/', verbose_name='Favicon'),
        ),
    ]
