# Generated by Django 5.2.9 on 2026-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_configuracaoescola_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='certificado_escolar',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='comprovativo_pagamento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='copia_bi',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='tipo_inscricao',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='receber_emails_sistema',
            field=models.BooleanField(default=True, verbose_name='Deseja receber emails do sistema?'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('super_admin', 'Super Administrador (TI)'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('secretario_academico', 'Secretário Académico'), ('daac', 'Chefe de Departamento para Assuntos Académico (DAAC)'), ('financeiro', 'Responsável Financeiro'), ('bibliotecario', 'Bibliotecário'), ('rh', 'Gestor de Recursos Humanos'), ('professor', 'Docente (Professor)'), ('coordenador', 'Coordenador'), ('aluno', 'Aluno')], default='pendente', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
