# Generated by Django 5.2.9 on 2026-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_inscricao_certificado_escolar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='email',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='arquivo_bi',
            field=models.FileField(blank=True, help_text='Tamanho máximo: 5MB', null=True, upload_to='estudantes/documentos/bi/', verbose_name='Cópia do BI (PDF ou Imagem)'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='arquivo_certificado',
            field=models.FileField(blank=True, help_text='Tamanho máximo: 5MB', null=True, upload_to='estudantes/documentos/certificados/', verbose_name='Certificado/Habilitação (PDF ou Imagem)'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status_inscricao',
            field=models.CharField(choices=[('submetida', 'Submetida'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='submetida', max_length=20, verbose_name='Estado da Inscrição'),
        ),
    ]
