# Generated by Django 5.2.9 on 2026-01-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_inscricao_nome_completo_inscricao_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
