# Generated by Django 5.2.9 on 2026-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_inscricao_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='responsavel_legal_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Contacto'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='responsavel_legal_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='responsavel_legal_vinculo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grau/Vínculo'),
        ),
    ]
