# Generated by Django 5.2.9 on 2026-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_inscricao_responsavel_legal_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='data_fim_lectivo',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Aulas'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='data_inicio_lectivo',
            field=models.DateField(blank=True, null=True, verbose_name='Início das Aulas'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Notas'),
        ),
    ]
