# Generated by Django 5.2.9 on 2026-01-10 08:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_anoacademico_data_fim_lectivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoacademico',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Ano Académico', 'verbose_name_plural': 'Anos Académicos'},
        ),
        migrations.AlterUniqueTogether(
            name='anoacademico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='ano_atual',
            field=models.BooleanField(default=False, verbose_name='Ano Atual'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='codigo',
            field=models.CharField(default='0000/0000', max_length=20, unique=True, verbose_name='Código (ex: 2024/2025)'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='estado',
            field=models.CharField(choices=[('PLANEADO', 'Planeado'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='PLANEADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='descricao',
            field=models.CharField(default='Ano Académico', max_length=255, verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='ano_fim',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='ano_inicio',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='data_fim_lectivo',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='data_inicio_lectivo',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='status',
        ),
    ]
