# Generated by Django 5.2.9 on 2026-01-10 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_anoacademico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='pagamentosubscricao',
            options={'verbose_name': 'Pagamento de Subscrição', 'verbose_name_plural': 'Pagamentos de Subscrição'},
        ),
        migrations.AlterModelOptions(
            name='pai',
            options={'verbose_name': 'Pai/Encarregado', 'verbose_name_plural': 'Pais/Encarregados'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='recuperacaosenha',
            options={'verbose_name': 'Recuperação de Senha', 'verbose_name_plural': 'Recuperações de Senha'},
        ),
        migrations.AlterModelOptions(
            name='subscricao',
            options={'verbose_name': 'Subscrição', 'verbose_name_plural': 'Subscrições'},
        ),
        migrations.RemoveField(
            model_name='pai',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='pai',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='recuperacaosenha',
            name='codigo_otp',
        ),
        migrations.RemoveField(
            model_name='recuperacaosenha',
            name='token',
        ),
        migrations.AddField(
            model_name='pai',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='core.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='recuperacaosenha',
            name='codigo',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(help_text='Template do documento (HTML/Text)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='secao',
            field=models.CharField(choices=[('geral', 'Geral'), ('inscricao', 'Inscrição'), ('financeiro', 'Financeiro'), ('academico', 'Académico')], default='geral', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='global_notificacao',
            field=models.BooleanField(default=False, help_text='Se marcado, todos os usuários verão esta notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida_por',
            field=models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Informação'), ('AVISO', 'Aviso'), ('URGENTE', 'Urgente'), ('SISTEMA', 'Sistema')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='comprovante',
            field=models.FileField(upload_to='pagamentos/comprovantes/'),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='data_pagamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='data_submissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='plano_escolhido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='recibo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pagamentos/recibos/'),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='subscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.subscricao'),
        ),
        migrations.AlterField(
            model_name='pagamentosubscricao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('pedagogico', 'Pedagógico'), ('financeiro', 'Financeiro'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('estudante', 'Estudante'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='data_expiracao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='email_enviado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='telefone_enviado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='tipo',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recuperacaosenha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='data_expiracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='nome_escola',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='plano',
            field=models.CharField(choices=[('trial', 'Trial (15 dias)'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome (ex: 1º Semestre / 2º Semestre)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20, verbose_name='Estado')),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_lectivos', to='core.anoacademico', verbose_name='Ano Lectivo')),
            ],
            options={
                'verbose_name': 'Período Lectivo',
                'verbose_name_plural': 'Períodos Lectivos',
                'ordering': ['ano_lectivo', 'data_inicio'],
            },
        ),
    ]
