# Generated by Django 5.2.9 on 2026-01-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ano_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.anoacademico', verbose_name='Ano Académico'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='periodo_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodolectivo', verbose_name='Período Lectivo'),
        ),
    ]
