# Generated by Django 5.2.9 on 2026-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_inscricao_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='estudantes/pagamentos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='hash_seguranca',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash de Segurança'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='metodo_pagamento',
            field=models.CharField(choices=[('referencia', 'Referência Bancária'), ('multicaixa', 'Multicaixa (Transferência/Depósito)')], default='multicaixa', max_length=20, verbose_name='Método de Pagamento'),
        ),
    ]
