# Generated by Django 5.2.10 on 2026-01-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_inscricao_comprovativo_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=50, verbose_name='Versão (Ano ou Código)')),
                ('duracao_anos', models.PositiveIntegerField(default=4, verbose_name='Duração (Anos)')),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('obsoleto', 'Obsoleto')], default='rascunho', max_length=20, verbose_name='Estado')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_curriculares', to='core.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Grade Curricular',
                'verbose_name_plural': 'Grades Curriculares',
                'ordering': ['curso', '-versao'],
                'unique_together': {('curso', 'versao')},
            },
        ),
    ]
