# Generated by Django 5.2.10 on 2026-01-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_gradecurricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecurricular',
            name='tipo_periodo',
            field=models.CharField(choices=[('semestre', 'Semestral'), ('trimestre', 'Trimestral')], default='semestre', max_length=20, verbose_name='Tipo de Período'),
        ),
    ]
