# Generated by Django 5.2.10 on 2026-01-12 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_gradecurricular_tipo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='creditos',
            field=models.PositiveIntegerField(default=0, verbose_name='Créditos'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='grade_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='core.gradecurricular', verbose_name='Grade Curricular'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('opcional', 'Opcional')], default='obrigatoria', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre_curricular',
            field=models.PositiveIntegerField(default=1, verbose_name='Período Curricular'),
        ),
    ]
