# Generated by Django 5.2.10 on 2026-01-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_disciplina_creditos_disciplina_grade_curricular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='sucessoras', to='core.disciplina', verbose_name='Pré-requisitos'),
        ),
    ]
