# Generated by Django 5.2.10 on 2026-01-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_disciplina_prerequisitos'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='area_conhecimento',
            field=models.CharField(choices=[('nuclear', 'Nuclear/Científica'), ('complementar', 'Complementar'), ('geral', 'Formação Geral'), ('projeto', 'Projeto/Estágio')], default='nuclear', max_length=30, verbose_name='Área de Conhecimento'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='requer_duas_positivas_para_dispensa',
            field=models.BooleanField(default=True, verbose_name='Requer Positiva nas Provas Parcelares para Dispensa'),
        ),
    ]
