# Generated by Django 6.0.1 on 2026-01-12 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_disciplina_area_conhecimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='lei_7_aplicavel',
            field=models.BooleanField(default=False, verbose_name='Aplicar Lei 7 (Reprovação Direta se Média < 7)'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='requer_duas_positivas_para_dispensa',
            field=models.BooleanField(default=False, verbose_name='Requer Positiva nas Provas Parcelares para Dispensa'),
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('INSCRICAO', 'Inscrição'), ('MATRICULA', 'Matrícula'), ('TESTE', 'Teste / Avaliação'), ('EXAMES', 'Exames'), ('FERIAS', 'Férias'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20, verbose_name='Estado')),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.anoacademico', verbose_name='Ano Lectivo')),
            ],
            options={
                'verbose_name': 'Evento de Calendário',
                'verbose_name_plural': 'Eventos de Calendário',
                'ordering': ['data_inicio'],
            },
        ),
    ]
