# Generated by Django 6.0.1 on 2026-01-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_disciplina_lei_7_aplicavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='dia_inicio_multa',
            field=models.PositiveIntegerField(default=11, verbose_name='Dia de Início da Multa'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='dia_limite_multa',
            field=models.PositiveIntegerField(default=30, verbose_name='Dia Limite para Pagamento com Multa'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='dia_pagamento_limite',
            field=models.PositiveIntegerField(default=10, verbose_name='Dia Limite de Pagamento (sem multa)'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='percentagem_multa_diaria',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='% Multa Diária Adicional'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='percentagem_multa_inicial',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Multa Inicial'),
        ),
    ]
