# Generated by Django 6.0.1 on 2026-01-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_anoacademico_dia_inicio_multa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='cobrar_propinas',
            field=models.BooleanField(default=True, verbose_name='Cobrar Propinas/Mensalidades'),
        ),
    ]
