# Generated by Django 6.0.1 on 2026-01-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_anoacademico_cobrar_propinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='bloquear_estudante_atrasado',
            field=models.BooleanField(default=True, verbose_name='Bloquear Estudante em Atraso'),
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='dia_bloqueio_estudante',
            field=models.PositiveIntegerField(default=15, verbose_name='Dia de Bloqueio Automático'),
        ),
    ]
