# Generated by Django 6.0.1 on 2026-01-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_anoacademico_bloquear_estudante_atrasado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='bloqueado_por_divida',
            field=models.BooleanField(default=False, verbose_name='Bloqueado por Dívida'),
        ),
    ]
