# Generated by Django 6.0 on 2026-01-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_anoacademico_bloqueado_por_divida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='grau',
            field=models.CharField(choices=[('licenciatura', 'Licenciatura'), ('mestrado', 'Mestrado'), ('doutoramento', 'Doutoramento'), ('especialidade', 'Especialidade'), ('ensino_medio', 'Ensino Médio')], default='licenciatura', max_length=20, verbose_name='Grau'),
        ),
    ]
