# Generated by Django 6.0.1 on 2026-01-12 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_curso_grau'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Nível')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nível Académico',
                'verbose_name_plural': 'Níveis Académicos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='grau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.nivelacademico', verbose_name='Grau Académico'),
        ),
    ]
