# Generated by Django 5.2.10 on 2026-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_nivelacademico_alter_curso_grau'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
