# Generated by Django 5.2.10 on 2026-01-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_nivelacademico_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='creditos_minimos',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Mínimo de Créditos'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='duracao_padrao',
            field=models.PositiveIntegerField(default=4, verbose_name='Duração Padrão (Anos)'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='periodos_por_ano',
            field=models.PositiveIntegerField(default=2, verbose_name='Número de Períodos por Ano'),
        ),
    ]
