# Generated by Django 5.2.10 on 2026-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_nivelacademico_creditos_minimos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='escala_notas_max',
            field=models.IntegerField(default=20, verbose_name='Escala Máxima'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='escala_notas_min',
            field=models.IntegerField(default=0, verbose_name='Escala Mínima'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='limite_reprovacoes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Reprovações'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='media_minima_progressao',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Média Mínima para Progressão'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='nota_minima_aprovacao',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Nota Mínima de Aprovação'),
        ),
    ]
