# Generated by Django 5.2.10 on 2026-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_nivelacademico_escala_notas_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='documentos_obrigatorios',
            field=models.TextField(blank=True, verbose_name='Documentos obrigatórios'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='exige_teste_admissao',
            field=models.BooleanField(default=False, verbose_name='Exige teste de admissão?'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='nivel_entrada_exigido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nível de entrada exigido'),
        ),
    ]
