# Generated by Django 5.2.10 on 2026-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_nivelacademico_documentos_obrigatorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='regime_modular',
            field=models.BooleanField(default=False, verbose_name='Modular'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='regime_pos_laboral',
            field=models.BooleanField(default=False, verbose_name='Pós-laboral'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='regime_regular',
            field=models.BooleanField(default=True, verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='turno_manha',
            field=models.BooleanField(default=True, verbose_name='Manhã'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='turno_noite',
            field=models.BooleanField(default=False, verbose_name='Noite'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='turno_tarde',
            field=models.BooleanField(default=True, verbose_name='Tarde'),
        ),
    ]
