# Generated by Django 5.2.10 on 2026-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_nivelacademico_regime_modular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='base_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Base legal'),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='entidade_acreditadora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entidade acreditadora'),
        ),
    ]
