# Generated by Django 6.0.1 on 2026-01-13 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_nivelacademico_base_legal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='grau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.nivelacademico', verbose_name='Grau Académico'),
        ),
    ]
