# Generated by Django 6.0.1 on 2026-01-13 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_curso_grau'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='tipo_periodo',
            field=models.CharField(choices=[('semestre', 'Semestres'), ('trimestre', 'Trimestres')], default='semestre', max_length=20, verbose_name='Tipo de Período'),
        ),
        migrations.AlterField(
            model_name='nivelacademico',
            name='escala_notas_max',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Escala Máxima'),
        ),
        migrations.AlterField(
            model_name='nivelacademico',
            name='nota_minima_aprovacao',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota Mínima de Aprovação'),
        ),
    ]
