# Generated by Django 6.0.1 on 2026-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_nivelacademico_tipo_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecurricular',
            name='max_disciplinas_atraso',
            field=models.PositiveIntegerField(default=2, verbose_name='Limite de Disciplinas em Atraso'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='media_aprovacao_direta',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=4, verbose_name='Média para Dispensa/Aprovação Direta'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='media_minima_exame',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Média Mínima para Exame'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='media_reprovacao_direta',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=4, verbose_name='Média para Reprovação Direta'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='permite_exame_especial',
            field=models.BooleanField(default=True, verbose_name='Permite Exame Especial (Recurso)'),
        ),
    ]
