# Generated by Django 6.0.1 on 2026-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_gradecurricular_max_disciplinas_atraso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecurricular',
            name='precedencia_automatica_romana',
            field=models.BooleanField(default=True, verbose_name='Ativar Precedência Automática (I, II, III, IV)'),
        ),
    ]
