# Generated by Django 5.2.10 on 2026-01-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_gradecurricular_precedencia_automatica_romana'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='is_projeto',
            field=models.BooleanField(default=False, verbose_name='É Disciplina de Projeto?'),
        ),
    ]
