# Generated by Django 5.2.10 on 2026-01-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_disciplina_is_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentagem_prova_continua', models.PositiveIntegerField(default=40, verbose_name='% Prova Contínua')),
                ('percentagem_exame_final', models.PositiveIntegerField(default=60, verbose_name='% Exame Final')),
                ('minimo_presenca_obrigatoria', models.PositiveIntegerField(default=75, verbose_name='% Mínimo Presença')),
                ('anos_com_barreira_atraso', models.CharField(default='3,5', help_text='Anos que exigem zero atrasos (ex: 3,5)', max_length=100)),
                ('limite_semestres_trancamento', models.PositiveIntegerField(default=2, verbose_name='Máximo Semestres Trancamento')),
                ('limite_tempo_exclusao_anos', models.PositiveIntegerField(default=1, verbose_name='Anos para Exclusão por Inatividade')),
            ],
            options={
                'verbose_name': 'Configuração Académica Global',
                'verbose_name_plural': 'Configurações Académicas Globais',
            },
        ),
    ]
