# Generated by Django 5.2.10 on 2026-01-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_configuracaoacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='peso_avaliacao_continua',
            field=models.PositiveIntegerField(default=1, help_text='Peso da avaliação contínua no cálculo final (ex: 1)', verbose_name='Peso Avaliação Contínua'),
        ),
    ]
