# Generated by Django 5.2.10 on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_configuracaoacademica_peso_avaliacao_continua'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='ativar_barreiras_progressao',
            field=models.BooleanField(default=True, verbose_name='Ativar Barreiras de Progressão'),
        ),
    ]
