# Generated by Django 5.2.10 on 2026-01-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_configuracaoacademica_ativar_barreiras_progressao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='permite_equivalencia_automatica',
            field=models.BooleanField(default=True, verbose_name='Permite Equivalência Automática'),
        ),
    ]
