# Generated by Django 5.2.10 on 2026-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_configuracaoacademica_permite_equivalencia_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecurricular',
            name='aplicar_lei_da_setima',
            field=models.BooleanField(default=True, help_text='Média < 7 em avaliações parciais implica reprovação direta', verbose_name="Aplicar 'Lei da Sétima'"),
        ),
    ]
