# Generated by Django 5.2.10 on 2026-01-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_gradecurricular_aplicar_lei_da_setima'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='aplicar_regras_projeto_especiais',
            field=models.BooleanField(default=True, help_text='Ativa regras diferenciadas para disciplinas de projeto (Exame=Projeto, etc)', verbose_name='Aplicar Regras Especiais para Projeto'),
        ),
    ]
