# Generated by Django 5.2.10 on 2026-01-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_configuracaoacademica_aplicar_regras_projeto_especiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='aplicar_lei_da_setima_global',
            field=models.BooleanField(default=True, help_text='Ativa a regra de média mínima 7 em avaliações parciais para toda a escola', verbose_name='Aplicar Lei da Sétima Institucional'),
        ),
    ]
