# Generated by Django 5.2.10 on 2026-01-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_configuracaoacademica_aplicar_lei_da_setima_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='dispensa_apenas_complementares',
            field=models.BooleanField(default=False, help_text='Se ativo, disciplinas nucleares/obrigatórias não permitem dispensa', verbose_name='Dispensa apenas disciplinas complementares'),
        ),
        migrations.AddField(
            model_name='configuracaoacademica',
            name='exigir_duas_positivas_dispensa',
            field=models.BooleanField(default=True, help_text='Se ativo, qualquer nota negativa nas parcelares bloqueia a dispensa, mesmo com média >= 14', verbose_name='Exigir duas provas parcelares positivas para dispensa'),
        ),
    ]
