# Generated by Django 5.2.10 on 2026-01-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_configuracaoacademica_dispensa_apenas_complementares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='max_disciplinas_atraso',
            field=models.PositiveIntegerField(default=2, verbose_name='Limite Cadeiras Atraso'),
        ),
        migrations.AddField(
            model_name='configuracaoacademica',
            name='media_aprovacao_direta',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=4, verbose_name='Média Aprovação Direta'),
        ),
        migrations.AddField(
            model_name='configuracaoacademica',
            name='media_minima_exame',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Média Mínima Exame'),
        ),
        migrations.AddField(
            model_name='configuracaoacademica',
            name='media_reprovacao_direta',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=4, verbose_name='Média Reprovação Direta'),
        ),
        migrations.AddField(
            model_name='configuracaoacademica',
            name='permite_exame_especial',
            field=models.BooleanField(default=True, verbose_name='Permite Exames Especiais'),
        ),
        migrations.AddField(
            model_name='configuracaoacademica',
            name='precedencia_automatica_romana',
            field=models.BooleanField(default=True, verbose_name='Precedência Automática (I, II, III...)'),
        ),
    ]
