# Generated by Django 5.2.10 on 2026-01-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_configuracaoacademica_max_disciplinas_atraso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Académica'), ('FINANCEIRA', 'Financeira')], max_length=20)),
                ('motivo', models.TextField(verbose_name='Motivo / Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('estagio_atual', models.CharField(choices=[('SECRETARIA', 'Secretaria / DAAC'), ('DIRETOR', 'Diretor'), ('ADMIN', 'Administrador'), ('SUPER_ADMIN', 'Super Administrador')], default='SECRETARIA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
