# Generated by Django 5.2.10 on 2026-01-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ano_curricular',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Ano Curricular'),
        ),
    ]
