# Generated by Django 5.2.10 on 2026-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_disciplina_ano_curricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='usar_creditos',
            field=models.BooleanField(default=True, help_text='Se desativado, o campo de créditos será opcional/oculto', verbose_name='Usar Sistema de Créditos'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Créditos'),
        ),
    ]
