# Generated by Django 5.2.10 on 2026-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_configuracaoacademica_usar_creditos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre_curricular',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Período Curricular'),
        ),
    ]
