# Generated by Django 5.2.10 on 2026-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_disciplina_semestre_curricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('laboratorio', 'Laboratório')], default='normal', max_length=20, verbose_name='Tipo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Estado (Ativa)')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
