# Generated by Django 5.2.10 on 2026-01-14 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_sala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'curso')},
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_academico',
            field=models.PositiveIntegerField(default=1, verbose_name='Ano Académico (ex: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_lectivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_academica', to='core.anoacademico'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='capacidade',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='turma',
            name='periodo_curricular',
            field=models.PositiveIntegerField(default=1, verbose_name='Semestre/Trimestre'),
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=10),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_academica', to='core.curso'),
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'perfil__nivel_acesso': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'unique_together': {('turma', 'disciplina')},
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplinas_turma',
            field=models.ManyToManyField(related_name='turmas_disciplina', through='core.TurmaDisciplina', to='core.disciplina'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ano_letivo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor_titular',
        ),
    ]
