# Generated by Django 5.2.10 on 2026-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_turma_options_alter_turma_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='sexo',
        ),
        migrations.AddField(
            model_name='professor',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='professor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=20, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='professor',
            name='municipio_provincia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Município / Província'),
        ),
        migrations.AddField(
            model_name='professor',
            name='nacionalidade',
            field=models.CharField(default='Angolana', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bilhete_identidade',
            field=models.CharField(max_length=50, verbose_name='Nº do BI'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Especialidade'),
        ),
    ]
