# Generated by Django 5.2.10 on 2026-01-15 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_professor_sexo_professor_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='area_formacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Área de Formação'),
        ),
        migrations.AddField(
            model_name='professor',
            name='categoria',
            field=models.CharField(blank=True, choices=[('assistente_estagiario', 'Assistente Estagiário'), ('assistente', 'Assistente'), ('auxiliar', 'Auxiliar'), ('associado', 'Associado'), ('professor_catedratico', 'Professor Catedrático'), ('docente_convidado', 'Docente Convidado')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='professor',
            name='codigo_professor',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código do Professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='professor',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='professor',
            name='grau_academico',
            field=models.CharField(blank=True, choices=[('licenciado', 'Licenciado'), ('mestre', 'Mestre'), ('doutor', 'Doutor')], max_length=20, verbose_name='Grau Académico'),
        ),
        migrations.AddField(
            model_name='professor',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('efetivo', 'Efetivo'), ('colaborador', 'Colaborador'), ('estagiario', 'Estagiário')], max_length=20, verbose_name='Tipo de Vínculo'),
        ),
    ]
