# Generated by Django 5.2.10 on 2026-01-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_professor_area_formacao_professor_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidade'),
        ),
    ]
