# Generated by Django 5.2.10 on 2026-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_professor_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='bilhete_identidade',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nº do BI'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_completo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefone'),
        ),
    ]
