# Generated by Django 5.2.10 on 2026-01-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_professor_bilhete_identidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turmadisciplina',
            options={'verbose_name': 'Horário de Aula', 'verbose_name_plural': 'Horários de Aula'},
        ),
        migrations.AlterUniqueTogether(
            name='turmadisciplina',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='tempo_tipo',
            field=models.CharField(blank=True, choices=[('1_semestre', '1º Semestre'), ('2_semestre', '2º Semestre'), ('trimestre', 'Trimestre')], max_length=20, null=True),
        ),
    ]
