# Generated by Django 5.2.10 on 2026-01-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_turmadisciplina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodolectivo',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Período Corrente'),
        ),
    ]
