# Generated by Django 5.2.10 on 2026-01-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_periodolectivo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoescola',
            name='cargo_responsavel_assinatura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cargo do Responsável (Assinatura)'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='cargo_responsavel_visto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cargo do Responsável (Visto)'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='grau_responsavel_assinatura',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grau Académico (Assinatura)'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='grau_responsavel_visto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grau Académico (Visto)'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='nome_responsavel_assinatura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Responsável (Assinatura)'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='nome_responsavel_visto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Responsável (Visto)'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='tipo_ensino',
            field=models.CharField(choices=[('superior', 'Ensino Superior'), ('geral', 'Ensino Geral')], default='superior', max_length=20, verbose_name='Tipo de Instituição'),
        ),
    ]
