# Generated by Django 5.2.10 on 2026-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_configuracaoescola_cargo_responsavel_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoescola',
            name='decreto_legalidade',
            field=models.CharField(blank=True, help_text='Decreto que aprova a legalidade da instituição', max_length=500, null=True, verbose_name='Decreto de Legalidade'),
        ),
    ]
