# Generated by Django 5.2.10 on 2026-01-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_configuracaoescola_decreto_legalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tempos_aula', models.PositiveIntegerField(default=2, help_text='Número de tempos/horas aula nesta sessão')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.professor')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
            },
        ),
        migrations.CreateModel(
            name='RegistroPresencaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('lecionada', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.horarioaula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'verbose_name': 'Registro de Carga Letiva',
                'verbose_name_plural': 'Registros de Carga Letiva',
            },
        ),
    ]
