# Generated by Django 5.2.10 on 2026-01-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_horarioaula_registropresencaprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioaula',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira')]),
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_disciplinas', to='core.professor')),
            ],
            options={
                'verbose_name': 'Professor Disciplina',
                'verbose_name_plural': 'Professor Disciplinas',
                'unique_together': {('professor', 'disciplina')},
            },
        ),
    ]
