# Generated by Django 5.2.10 on 2026-01-16 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_horarioaula_dia_semana_professordisciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudantes', to='core.aluno')),
                ('ano_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudantes', to='core.anoacademico')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudantes', to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudantes', to='core.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudantes', to='core.turma')),
            ],
            options={
                'verbose_name': 'Nota do Estudante',
                'verbose_name_plural': 'Notas dos Estudantes',
                'unique_together': {('ano_academico', 'turma', 'disciplina', 'aluno')},
            },
        ),
    ]
