# Generated by Django 5.2.10 on 2026-01-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_notaestudante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Privilégio')),
                ('codigo', models.SlugField(max_length=100, unique=True, verbose_name='Código Interno')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('modulo', models.CharField(choices=[('SA', 'Secretaria Acadêmica'), ('RH', 'Recursos Humanos'), ('FIN', 'Financeiro'), ('PED', 'Pedagógico'), ('ADM', 'Administrativo')], max_length=5, verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Privilégio',
                'verbose_name_plural': 'Privilégios',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='privilegios',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='core.privilegio', verbose_name='Privilégios'),
        ),
    ]
