# Generated by Django 5.2.10 on 2026-01-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_privilegio_perfilusuario_privilegios'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala', verbose_name='Sala Principal'),
        ),
    ]
