# Generated by Django 5.2.10 on 2026-01-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_turma_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoacademica',
            name='criterio_desempate',
            field=models.CharField(choices=[('idade_desc', 'Mais Velho primeiro'), ('idade_asc', 'Mais Novo primeiro'), ('inscricao_asc', 'Ordem de Inscrição (Primeiros primeiro)')], default='idade_desc', max_length=50, verbose_name='Critério de Desempate'),
        ),
    ]
