# Generated by Django 5.2.10 on 2026-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_configuracaoacademica_criterio_desempate'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL Amigável)'),
        ),
        migrations.AlterField(
            model_name='configuracaoacademica',
            name='criterio_desempate',
            field=models.CharField(choices=[('idade_desc', 'Mais Velho primeiro'), ('idade_asc', 'Mais Novo primeiro'), ('inscricao_asc', 'Ordem de Inscrição (Primeiros primeiro)'), ('sexo_f', 'Prioridade Feminino'), ('sexo_m', 'Prioridade Masculino'), ('sexo_f_novo', 'Feminino e Mais Novo'), ('sexo_f_velho', 'Feminino e Mais Velho')], default='idade_desc', max_length=50, verbose_name='Critério de Desempate'),
        ),
    ]
