# Generated by Django 5.2.10 on 2026-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_curso_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadados ERP (JSON)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('arquivado', 'Arquivado'), ('obsoleto', 'Obsoleto')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='versao',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='secao',
            field=models.CharField(choices=[('geral', 'Geral'), ('inscricao', 'Inscrição'), ('financeiro', 'Financeiro'), ('academico', 'Académico'), ('rh', 'Recursos Humanos'), ('biblioteca', 'Biblioteca'), ('inventario', 'Inventário')], default='geral', max_length=20),
        ),
    ]
