# Generated by Django 5.2.10 on 2026-01-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_documento_metadata_documento_status_documento_versao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala'),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='tipo_aula',
            field=models.CharField(choices=[('teorica', 'Teórica'), ('pratica', 'Prática'), ('laboratorio', 'Laboratório'), ('seminario', 'Seminário')], default='teorica', max_length=20),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='core.turma'),
        ),
        migrations.AlterField(
            model_name='horarioaula',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')]),
        ),
    ]
