from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_redirect, name='index_redirect'),
    path('painel/', views.index, name='painel_principal'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('inscricao/<int:curso_id>/', views.inscricao_create, name='inscricao_create'),
    path('inscricao/<str:numero>/pdf/', views.gerar_pdf_confirmacao, name='gerar_pdf_confirmacao'),
    path('minha-conta/', views.perfil_usuario, name='perfil_usuario'),
    path('pagamento/', views.pagamento_subscricao_view, name='pagamento_subscription'),
    path('documentos/', views.gestao_documentos, name='gestao_documentos'),
    path('documentos/novo/', views.documento_criar, name='documento_criar'),
    path('documentos/<int:doc_id>/editar/', views.documento_editar, name='documento_editar'),
    path('documentos/<int:doc_id>/deletar/', views.documento_deletar, name='documento_deletar'),
    path('documentos/<int:doc_id>/visualizar/', views.documento_visualizar, name='documento_visualizar'),
    path('documentos/<int:doc_id>/pdf/', views.gerar_pdf_documento, name='gerar_pdf_documento'),
    
    # URLs para Gestão de Cursos
    path('cursos/', views.listar_cursos, name='listar_cursos'),
    path('cursos/novo/', views.criar_curso, name='criar_curso'),
    path('cursos/<int:curso_id>/detalhe/', views.detalhe_curso, name='detalhe_curso'),
    path('cursos/<int:curso_id>/editar/', views.editar_curso, name='editar_curso'),
    path('cursos/<int:curso_id>/deletar/', views.deletar_curso, name='deletar_curso'),
    path('cursos/<int:curso_id>/toggle/', views.toggle_curso_status, name='toggle_curso_status'),
    
    # URLs para Gestão de Utilizadores
    path('utilizadores/', views.listar_utilizadores, name='listar_utilizadores'),
    path('utilizadores/novo/', views.criar_utilizador, name='criar_utilizador'),
    path('utilizadores/<int:user_id>/editar/', views.editar_utilizador, name='editar_utilizador'),
    path('utilizadores/<int:user_id>/deletar/', views.deletar_utilizador, name='deletar_utilizador'),
    # URLs para Anos Académicos
    path('anos-academicos/', views.ano_academico_lista, name='ano_academico_lista'),
    path('anos-academicos/novo/', views.ano_academico_create, name='ano_academico_create'),
    path('anos-academicos/<int:pk>/editar/', views.ano_academico_edit, name='ano_academico_edit'),
    path('anos-academicos/<int:ano_id>/periodos/', views.periodo_lectivo_lista, name='periodo_lectivo_lista'),
    path('anos-academicos/<int:ano_id>/periodos/novo/', views.periodo_lectivo_create, name='periodo_lectivo_create'),
    path('periodos/<int:pk>/editar/', views.periodo_lectivo_edit, name='periodo_lectivo_edit'),
    
    # URLs para Menus do Painel Principal
    path('nova-matricula/', views.selecionar_tipo_matricula, name='nova_matricula'),
    path('candidatos/perfil/', views.perfil_candidato_login, name='perfil_candidato_login'),
    path('candidatos/painel/', views.painel_candidato, name='painel_candidato'),
    path('candidatos/lista/', views.lista_inscritos, name='lista_inscritos'),
    path('candidatos/lancamento-notas/', views.lancamento_notas, name='lancamento_notas'),
    path('candidatos/processar-aprovacao/', views.processar_aprovacao_vagas, name='processar_aprovacao_vagas'),
    path('consultar-aprovacao/', views.consultar_aprovacao, name='consultar_aprovacao'),
    path('admissao-estudantes/', views.admissao_estudantes, name='admissao_estudantes'),
    path('termo-renovacao/', views.termo_renovacao, name='termo_renovacao'),
    path('receber-documento-matricula/', views.receber_documento_matricula, name='receber_documento_matricula'),
    path('assiduidade/', views.assiduidade, name='assiduidade'),
    path('assiduidade-docentes/', views.assiduidade_docentes, name='assiduidade_docentes'),
    path('atribuicao-turmas/', views.atribuicao_turmas, name='atribuicao_turmas'),
    path('turma/<int:turma_id>/detalhes/', views.detalhe_turma, name='detalhe_turma'),
    path('professores/', views.listar_professores, name='listar_professores'),
    path('professores/novo/', views.criar_professor, name='criar_professor'),
    path('horarios/', views.gestao_horarios, name='gestao_horarios'),
    path('horarios/registrar/', views.registrar_horario, name='registrar_horario'),
    path('horarios/grade/', views.visualizar_grade, name='visualizar_grade'),
    path('horarios/lista/', views.listar_horarios, name='listar_horarios'),
    path('horarios/editar/<int:pk>/', views.editar_horario, name='editar_horario'),
    path('horarios/deletar/<int:pk>/', views.deletar_horario, name='deletar_horario'),
    path('configuracao-escola/', views.gestao_configuracao_escola, name='gestao_configuracao_escola'),
]
