# Generated by Django 5.2.9 on 2025-12-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_update_inscricao_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='documentos_entregues',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='encarregado_email',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='encarregado_local_trabalho',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='encarregado_nome',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='encarregado_parentesco',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='encarregado_profissao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='encarregado_telefone',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='login_usuario',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='notificacoes_email',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='notificacoes_sms',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='observacoes_documentacao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='senha_provisoria',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='telefone_alternativo',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_legal_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável Legal/Financeiro'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_legal_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Legal'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_legal_vinculo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grau/Vínculo Legal'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_pedagogico_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável Pedagógico'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_pedagogico_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Pedagógico'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_pedagogico_vinculo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grau/Vínculo Pedagógico'),
        ),
    ]
