# Generated by Django 5.2.9 on 2026-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_email_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='receber_emails_sistema',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificado_escolar',
            field=models.FileField(blank=True, null=True, upload_to='estudantes/documentos/', verbose_name='Certificado Escolar'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='estudantes/documentos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='copia_bi',
            field=models.FileField(blank=True, null=True, upload_to='estudantes/documentos/', verbose_name='Cópia do BI'),
        ),
    ]
