# Generated by Django 5.2.9 on 2026-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_inscricao_receber_emails_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='tipo_inscricao',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='online', max_length=20, verbose_name='Tipo de Inscrição'),
        ),
    ]
