# Generated by Django 5.2.9 on 2026-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_inscricao_email_inscricao_arquivo_bi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='apelido',
            field=models.CharField(default='', max_length=50, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nomes_meio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nomes do Meio'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=50, verbose_name='Primeiro Nome'),
        ),
    ]
